version: '3'
services:

  prometheus:
    image: prom/prometheus:latest
    container_name: monitoring_prometheus
    restart: unless-stopped
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    expose:
      - 9090
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:latest
    container_name: monitoring_grafana
    restart: unless-stopped
    links:
      - prometheus:prometheus
    expose:
      - 3000
    ports:
      - 3000:3000

  trace:
    container_name: trace
    image: openzipkin/zipkin
    restart: always
    ports:
      - 9411:9411
    expose:
      - 9411

  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: always
    hostname: mysql
    environment:
      MYSQL_DATABASE: 'vendas'
      MYSQL_USER: 'vendas'
      MYSQL_PASSWORD: 'vendas123'
      MYSQL_ROOT_PASSWORD: 'vendas123'
    ports:
      - 3307:3306
    expose:
      - 3307

  redis:
    container_name: redis
    image: redis
    restart: always
    hostname: redis
    ports:
      - 6379:6379
    expose:
      - 6379

  config:
    container_name: config
    image: gasparbarancelli/config:1.0
    restart: always
    environment:
      URI: 'https://github.com/gasparbarancelli/microservices-2.git'
    ports:
      - 8888:8888
    expose:
      - 8888

  discovery:
    container_name: discovery
    image: gasparbarancelli/discovery:2.0
    restart: always
    environment:
      CONFIG_SERVER_URL: 'http://config:8888'
    ports:
      - 8761:8761
    expose:
      - 8761
    depends_on:
      - config

  jms:
    container_name: jms
    image: rmohr/activemq
    restart: always
    ports:
      - 6161:61616
      - 8161:8161
    expose:
      - 6161
      - 8161

  produtos:
    container_name: produtos
    image: gasparbarancelli/produtos:3.0
    restart: always
    environment:
      CONFIG_SERVER_URL: 'http://config:8888'
      EUREKA_URL: 'http://discovery:8761/eureka/'
      JMS_URL: 'tcp://jms:61616'
      ZIPKIN_URL: 'http://trace:9411/'
    ports:
      - 8081:8081
    depends_on:
      - config
      - discovery
      - jms

  vendas:
    container_name: vendas
    image: gasparbarancelli/vendas:1.0
    restart: always
    environment:
      CONFIG_SERVER_URL: 'http://config:8888'
      EUREKA_URL: 'http://discovery:8761/eureka/'
      JMS_URL: 'tcp://jms:61616'
      ZIPKIN_URL: 'http://trace:9411/'
      MYSQL_HOST: 'mysql'
      MYSQL_PORT: 3306
    ports:
      - 8082:8082
    depends_on:
      - config
      - discovery
      - jms
      - prometheus

  cupons:
    container_name: cupons
    image: gasparbarancelli/cupons:1.0
    restart: always
    environment:
      CONFIG_SERVER_URL: 'http://config:8888'
      EUREKA_URL: 'http://discovery:8761/eureka/'
      JMS_URL: 'tcp://jms:61616'
      ZIPKIN_URL: 'http://trace:9411/'
      REDIS_HOST: 'redis'
    ports:
      - 8083:8083
    depends_on:
      - config
      - discovery
      - prometheus

  gateway:
    container_name: gateway
    image: gasparbarancelli/gateway:1.0
    restart: always
    environment:
      CONFIG_SERVER_URL: 'http://config:8888'
      EUREKA_URL: 'http://discovery:8761/eureka/'
    ports:
      - 8080:8080
    expose:
      - 8080
    depends_on:
      - config
      - discovery

  logspout:
    image: gliderlabs/logspout:v3
    command: 'udp://logstash:5000'
    links:
      - logstash
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock'
    depends_on:
      - elasticsearch
      - logstash
      - kibana

  logstash:
    image: logstash:2.1.1
    environment:
      - STDOUT=true
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
      - kibana
    command: 'logstash -e "input { udp { port => 5000 } } output { elasticsearch { hosts => elasticsearch } }"'

  kibana:
    image: kibana:4.1.2
    links:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  elasticsearch:
    image: elasticsearch:1.5.2
    ports:
      - 9200:9200
      - 9300:9300
